### ISSUE TITLE
Use rocketmq-client-java 5.0.6 CancellationException: Task was cancelled (UNIMPLEMENTED: HTTP status code 404) 

### ISSUE THREAD

**Issue by isMrZhang** [apache/rocketmq-docker#110]
**Programming Language of the Client**
Java

**Runtime Platform Environment**
Win 11

**RocketMQ Version of the Client/Server**
5.2.0 | 5.0.6

**Run or Compiler Version**
Oracle JDK 11.0.9

**Describe the Bug**
Start PushConsumer ERR org.apache.rocketmq.shaded.io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404

**Steps to Reproduce**
1. server 192.168.31.234 Deploy RocketMQ5.2.0 (https://github.com/apache/rocketmq-docker/blob/master/templates/docker-compose/rmq5-docker-compose.yml)
2. Start PushConsumer

**What Did You Expect to See?**
The consumer group is successfully started

**What Did You See Instead?**

> java.lang.IllegalStateException: Expected the service PushConsumerImpl-1 [FAILED] to be RUNNING, but the service has FAILED
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:381) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:305) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:165) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.client.java.impl.consumer.PushConsumerBuilderImpl.build(PushConsumerBuilderImpl.java:128) ~[rocketmq-client-java-5.0.6.jar:na]
> at com.xxx.push.mq.consumer.BaseConsumer.init(BaseConsumer.java:144) ~[classes/:na]
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
> at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.27.jar:5.3.27]
> at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:114) ~[spring-boot-2.7.12.jar:2.7.12]
> at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.12.jar:2.7.12]
> at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.12.jar:2.7.12]
> at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.12.jar:2.7.12]
> at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:82) ~[spring-boot-2.7.12.jar:2.7.12]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.7.12.jar:2.7.12]
> at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.12.jar:2.7.12]
> at com.xxx.core.launch.BladeApplication.run(XxxxApplication.java:34) ~[xxxx-core-launch-3.6.4.jar:na]
> at com.xxx.push.PushApplication.main(PushApplication.java:21) ~[classes/:na]
> Caused by: java.util.concurrent.ExecutionException: org.apache.rocketmq.shaded.io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
> invalid content-type: null
> trailers: Metadata(:status=404,date=Thu, 04 Jul 2024 02:07:23 GMT,server=Cowboy,content-length=0)
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.client.java.impl.ClientImpl.startUp(ClientImpl.java:188) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.client.java.impl.consumer.PushConsumerImpl.startUp(PushConsumerImpl.java:162) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.com.google.common.util.concurrent.Callables.lambda$threadRenaming$3(Callables.java:103) ~[rocketmq-client-java-5.0.6.jar:na]
> at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
> Caused by: org.apache.rocketmq.shaded.io.grpc.StatusRuntimeException: UNIMPLEMENTED: HTTP status code 404
> invalid content-type: null
> trailers: Metadata(:status=404,date=Thu, 04 Jul 2024 02:07:23 GMT,server=Cowboy,content-length=0)
> at org.apache.rocketmq.shaded.io.grpc.Status.asRuntimeException(Status.java:539) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[rocketmq-client-java-5.0.6.jar:na]
> at org.apache.rocketmq.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[rocketmq-client-java-5.0.6.jar:na]
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
> ... 1 common frames omitted

![image](https://github.com/user-attachments/assets/089a2dc7-983b-4c46-b512-7c1b46a02be0)
![image](https://github.com/user-attachments/assets/6e5173e1-baa8-4219-86dc-2efb87edb52a)
![image](https://github.com/user-attachments/assets/97773e2e-c625-4946-99a6-9151cc0db97d)

**Comment by isMrZhang** [comment]
public ClientConfiguration clientConfiguration() {
return ClientConfiguration.newBuilder()
.setEndpoints("192.168.31.234:8080")
.enableSsl(false)
// .setCredentialProvider(new StaticSessionCredentialsProvider(accessKeyId, accessKeySecret))
.build();
}

final ClientServiceProvider provider = ClientServiceProvider.loadService();
provider.newPushConsumerBuilder()
.setClientConfiguration(consumerConfig.clientConfiguration())
.setConsumptionThreadCount(CONSUME_THREAD_NUMS)
.setConsumerGroup(buildGroupId())
.setSubscriptionExpressions(Map.of(buildTopic(), new FilterExpression(String.join("||", buildTags()), FilterExpressionType.TAG)))
.setMessageListener(this::consumeMessage)
.build();
