### ISSUE TITLE
Deploy broker with docker-compose returns NoSuchAlgorithmException

### ISSUE THREAD

**Issue by xinghen110** [apache/rocketmq-docker#23]
### **docker-compose.yml**
version: '2'
services:
  #Service for nameserver
  namesrv:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rmqnamesrv
    ports:
      - 7931:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: apacherocketmq/rocketmq:4.6.0
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 7932:10909
      - 7933:10911
      - 7934:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.6.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.6.0/conf/broker.conf
  rmqconsole:
    image: styletang/rocketmq-console-ng
    restart: always
    container_name: rmqconsole
    ports:
      - 7935:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - namesrv

### **rocketmq_client.log**
2020-02-03 15:22:47,047 INFO RocketmqRemoting - name server address updated. NEW : [localhost:9876] , OLD: null
2020-02-03 15:22:47,047 INFO RocketmqClient - user specified name server address: localhost:9876
2020-02-03 15:22:47,047 INFO RocketmqClient - Created a new client Instance, InstanceIndex:0, ClientID:192.168.48.2@1580743367427, ClientConfig:ClientConfig [namesrvAddr=localhost:9876, clientIP=192.168.48.2, instanceName=1580743367427, clientCallbackExecutorThreads=4, pollNameServerInterval=30000, heartbeatBrokerInterval=30000, persistConsumerOffsetInterval=5000, pullTimeDelayMillsWhenException=1000, unitMode=false, unitName=null, vipChannelEnabled=false, useTLS=false, language=JAVA, namespace=null], ClientVersion:V4_6_0, SerializerType:JSON
2020-02-03 15:22:47,047 INFO RocketmqClient - Created new MQClientInstance for clientId:[192.168.48.2@1580743367427]
2020-02-03 15:22:47,047 INFO RocketmqCommon - Try to start service thread:PullMessageService started:false lastThread:null
2020-02-03 15:22:47,047 INFO RocketmqCommon - Try to start service thread:RebalanceService started:false lastThread:null
2020-02-03 15:22:47,047 INFO RocketmqClient - PullMessageService service started
2020-02-03 15:22:47,047 INFO RocketmqClient - RebalanceService service started
2020-02-03 15:22:47,047 INFO RocketmqClient - the producer [CLIENT_INNER_PRODUCER] start OK. sendMessageWithVIPChannel=false
2020-02-03 15:22:47,047 INFO RocketmqClient - the client factory [192.168.48.2@1580743367427] start OK
2020-02-03 15:22:47,047 INFO RocketmqClient - the adminExt [admin_ext_group] start OK
2020-02-03 15:22:47,047 INFO RocketmqRemoting - new name server is chosen. OLD: null , NEW: localhost:9876. namesrvIndex = 158
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2020-02-03 15:22:47,047 DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2020-02-03 15:22:47,047 INFO RocketmqRemoting - createChannel: begin to connect remote host[localhost:9876] asynchronously
2020-02-03 15:22:47,047 DEBUG io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.org.apache.rocketmq.remoting.protocol.RemotingCommandMatcher
2020-02-03 15:22:47,047 DEBUG io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.org.apache.rocketmq.remoting.protocol.RemotingCommandMatcher
2020-02-03 15:22:47,047 DEBUG io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.org.apache.rocketmq.remoting.protocol.RemotingCommandMatcher
2020-02-03 15:22:47,047 INFO RocketmqRemoting - NETTY CLIENT PIPELINE: CONNECT  UNKNOWN => ocalhost/127.0.0.1:9876
2020-02-03 15:22:47,047 INFO RocketmqRemoting - createChannel: connect remote host[localhost:9876] success, DefaultChannelPromise@7e07db1f(success)
2020-02-03 15:22:47,047 ERROR RocketmqAuthorize - [10015:signature-failed] unable to calculate a request signature. error=Algorithm HmacSHA1 not available
java.security.NoSuchAlgorithmException: Algorithm HmacSHA1 not available
	at javax.crypto.Mac.getInstance(Mac.java:181)
	at org.apache.rocketmq.acl.common.AclSigner.sign(AclSigner.java:57)
	at org.apache.rocketmq.acl.common.AclSigner.signAndBase64Encode(AclSigner.java:79)
	at org.apache.rocketmq.acl.common.AclSigner.calSignature(AclSigner.java:73)
	at org.apache.rocketmq.acl.common.AclSigner.calSignature(AclSigner.java:68)
	at org.apache.rocketmq.acl.common.AclUtils.calSignature(AclUtils.java:69)
	at org.apache.rocketmq.acl.common.AclClientRPCHook.doBeforeRequest(AclClientRPCHook.java:44)
	at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.doBeforeRpcHooks(NettyRemotingAbstract.java:172)
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:368)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1337)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:306)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:251)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.printClusterBaseInfo(ClusterListSubCommand.java:172)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:88)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:139)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:90)

**Comment by GongZhengMe** [comment]
I have the same problem...

**Comment by hustyangyi** [comment]
me too
