### ISSUE TITLE
 ClusterListSubCommand command Failed

### ISSUE THREAD

**Issue by GongZhengMe** [apache/rocketmq-docker#27]
Hello,I download rocketmq-docker today , and I just want to run the Cluster Mode. I don't modify any file,and just  deploy by the Readme.md. Unfortunately，It ‘s failed
docker-compose.yml:
```
version: '2'
services:
  #Service for nameserver
  namesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf

  #Service for another broker -- broker1
  broker1:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker-b
    links:
      - namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data1/broker/logs:/home/rocketmq/logs
      - ./data1/broker/store:/home/rocketmq/store
      - ./data1/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
```
I run `./play-docker-compose.sh` and run `docker ps` can see :
```
CONTAINER ID        IMAGE                           COMMAND                  CREATED              STATUS              PORTS                                                                                        NAMES
9d4576befd65        apacherocketmq/rocketmq:4.5.0   "sh mqbroker -c /opt…"   About a minute ago   Up About a minute   0.0.0.0:10909->10909/tcp, 9876/tcp, 0.0.0.0:10911-10912->10911-10912/tcp                     rmqbroker
f97e6f652907        apacherocketmq/rocketmq:4.5.0   "sh mqnamesrv"           About a minute ago   Up About a minute   10909/tcp, 0.0.0.0:9876->9876/tcp, 10911-10912/tcp                                           rmqnamesrv
```
But when I run `docker exec -it 9d4576befd65 ./mqadmin clusterList -n localhost:9876`
I see this bug:
```
org.apache.rocketmq.tools.command.SubCommandException: ClusterListSubCommand command failed
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:93)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:135)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:86)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:392)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1180)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:275)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:222)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.printClusterBaseInfo(ClusterListSubCommand.java:172)
	at org.apache.rocketmq.tools.command.cluster.ClusterListSubCommand.execute(ClusterListSubCommand.java:88)
	... 2 more
```
It is worth mentioning that I  exec `docker run -it  apacherocketmq/rocketmq:4.5.0 sh` and want to view the broker config ,so I run ` sh mqbroker -m` :
```
2020-03-19 17\:12\:15 INFO main - namesrvAddr=
2020-03-19 17\:12\:15 INFO main - brokerIP1=172.17.0.2
2020-03-19 17\:12\:15 INFO main - brokerName=46ff3293104e
2020-03-19 17\:12\:15 INFO main - brokerClusterName=DefaultCluster
2020-03-19 17\:12\:15 INFO main - brokerId=0
2020-03-19 17\:12\:15 INFO main - autoCreateTopicEnable=true
2020-03-19 17\:12\:15 INFO main - autoCreateSubscriptionGroup=true
2020-03-19 17\:12\:15 INFO main - msgTraceTopicName=RMQ_SYS_TRACE_TOPIC
2020-03-19 17\:12\:15 INFO main - traceTopicEnable=false
2020-03-19 17\:12\:15 INFO main - rejectTransactionMessage=false
2020-03-19 17\:12\:15 INFO main - fetchNamesrvAddrByAddressServer=false
2020-03-19 17\:12\:15 INFO main - transactionTimeOut=6000
2020-03-19 17\:12\:15 INFO main - transactionCheckMax=15
2020-03-19 17\:12\:15 INFO main - transactionCheckInterval=60000
2020-03-19 17\:12\:15 INFO main - aclEnable=false
2020-03-19 17\:12\:15 INFO main - storePathRootDir=/home/rocketmq/store
2020-03-19 17\:12\:15 INFO main - storePathCommitLog=/home/rocketmq/store/commitlog
2020-03-19 17\:12\:15 INFO main - flushIntervalCommitLog=500
2020-03-19 17\:12\:15 INFO main - commitIntervalCommitLog=200
2020-03-19 17\:12\:15 INFO main - flushCommitLogTimed=false
2020-03-19 17\:12\:15 INFO main - deleteWhen=04
2020-03-19 17\:12\:15 INFO main - fileReservedTime=72
2020-03-19 17\:12\:15 INFO main - maxTransferBytesOnMessageInMemory=262144
2020-03-19 17\:12\:15 INFO main - maxTransferCountOnMessageInMemory=32
2020-03-19 17\:12\:15 INFO main - maxTransferBytesOnMessageInDisk=65536
2020-03-19 17\:12\:15 INFO main - maxTransferCountOnMessageInDisk=8
2020-03-19 17\:12\:15 INFO main - accessMessageInMemoryMaxRatio=40
2020-03-19 17\:12\:15 INFO main - messageIndexEnable=true
2020-03-19 17\:12\:15 INFO main - messageIndexSafe=false
2020-03-19 17\:12\:15 INFO main - haMasterAddress=
2020-03-19 17\:12\:15 INFO main - brokerRole=ASYNC_MASTER
2020-03-19 17\:12\:15 INFO main - flushDiskType=ASYNC_FLUSH
2020-03-19 17\:12\:15 INFO main - cleanFileForciblyEnable=true
2020-03-19 17\:12\:15 INFO main - transientStorePoolEnable=false
```
above this result , I find the namesrvAddr is empty , So I think maybe the broker or broker cluster don't start well . So I can't verify the cluster well like ReadMe.md

**Comment by xiao-ma-nong** [comment]
解决了 我也遇到了，我没有用docker

**Comment by liuzhaomax** [comment]
如果是rmq的console遇到这个问题，需要检查是否docker-compose文件的console编排有没有设置环境变量 NAMESRV_ADDR: "rocketmqnamesrv:9876" ，（rocketmqnamesrv 是namesrv宿主机ip）

**Comment by tinarooot** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
