### ISSUE TITLE
Unable to start Broker using Docker Compose

### ISSUE THREAD

**Issue by CyJaySong** [apache/rocketmq-docker#85]
The issue tracker is **ONLY** used for bug report(feature request need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as the following:

**BUG REPORT**

1. Please describe the issue you observed:

```
cd rocketmq-docker/templates/docker-compose
vim docker-composite. yml # Modify the image version in the docker-composite. yml to 5.1.3
docker compose up -d
```

```
00:52:40,655 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [io.opentelemetry.exporter.logging.LoggingMetricExporter] to false
00:52:40,655 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [RocketmqBrokerMetricsAppender] to Logger[io.opentelemetry.exporter.logging.LoggingMetricExporter]
00:52:40,655 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
00:52:40,655 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [DefaultSiftingAppender] to Logger[ROOT]
00:52:40,655 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.DefaultProcessor@5bb21b69 - End of configuration.
00:52:40,656 |-INFO in org.apache.rocketmq.common.logging.JoranConfiguratorExt@6b9651f3 - Registering current configuration as safe fallback point

java.lang.NullPointerException
	at org.apache.rocketmq.broker.schedule.ScheduleMessageService.configFilePath(ScheduleMessageService.java:265)
	at org.apache.rocketmq.common.ConfigManager.persist(ConfigManager.java:84)
	at org.apache.rocketmq.broker.BrokerController.shutdownBasicService(BrokerController.java:1401)
	at org.apache.rocketmq.broker.BrokerController.shutdown(BrokerController.java:1464)
	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:242)
	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)
```

**Comment by LeeGode** [comment]
一样的错误，您解决了吗

**Comment by CyJaySong** [comment]
没呢

**Comment by minih-git** [comment]
store文件夹没有权限。给store文件夹设置777权限

**Comment by chaosky** [comment]
> store文件夹没有权限。给store文件夹设置777权限

最小权限设置，假设 data/broker/store/ 是 broker 的 store 目录。

chown -R 3000:3000 data/broker/store/
